<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="mybooking.aspx.cs" Inherits="Tour_Management.mybooking" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>My Booking</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Tour Management System</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link text-white" href="usercrud.aspx">Profile</a></li>
                    <li class="nav-item"><a class="nav-link text-white" href="DisplayTours.aspx">Tours</a></li>
                    <li class="nav-item"><a class="nav-link text-white" href="Order.aspx">Book Tour</a></li>
                    <li class="nav-item"><a class="nav-link text-white" href="mybooking.aspx">Bookings Info</a></li>
                    <li class="nav-item"><a class="nav-link text-white" href="Logout.aspx">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- MAIN CONTENT -->
    <div class="container mt-5">
        <h2 class="text-center mb-4 fw-bold">Your Current Booking</h2>
        <div class="card shadow p-4">
            <form id="form1" runat="server">
                <asp:GridView ID="GridView1" runat="server" CssClass="table table-bordered table-striped text-center"
    AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
    DataSourceID="SqlDataSource1" Width="100%" BorderColor="Black"
    DataKeyNames="TOUR_ID" GridLines="None"
    OnRowDataBound="GridView1_RowDataBound">
    <Columns>
        <asp:BoundField DataField="TOUR_ID" HeaderText="TOUR ID" ReadOnly="True" />
        <asp:BoundField DataField="TOUR_NAME" HeaderText="TOUR NAME" />
        <asp:BoundField DataField="PLACE" HeaderText="PLACE" />
        <asp:BoundField DataField="MobileNumber" HeaderText="MOBILE NUMBER" />
        <asp:BoundField DataField="FirstName" HeaderText="NAME" />
    </Columns>
    
    <HeaderStyle CssClass="table-dark" ForeColor="White" Font-Bold="True" />
</asp:GridView>


                <asp:SqlDataSource ID="SqlDataSource1" runat="server"
                    ConnectionString="<%$ ConnectionStrings:dbconnection %>"
                    SelectCommand="SELECT [TOUR_ID], [TOUR_NAME], [PLACE], [MobileNumber], [FirstName] FROM [booking]"
                    DeleteCommand="DELETE FROM [booking] WHERE [TOUR_ID]=@TOUR_ID">
                </asp:SqlDataSource>

                <asp:Label ID="lblMessage" runat="server" ForeColor="Green" Font-Bold="True"></asp:Label>
            </form>
        </div>
    </div>
</body>
</html>
